version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8080"
    volumes:
      - ./volumes/backend:/app
      - ./volumes/photo:/root/cars
    restart: on-failure
    command: >
      sh -c "/wait-for-it.sh db:3306 -- java -jar app.jar"

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=java_mar_2023
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=superpassword
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "5555:3306"
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./volumes/client/build:/usr/share/nginx/html
      - ./volumes/client/nginx.conf:/etc/nginx/conf.d/default.conf

